# Build
FROM rust as builder
WORKDIR /usr/src/mano-raje-sh
COPY backend/Cargo.toml backend/Cargo.lock ./
COPY backend/src ./src
RUN cargo build --release

# Run
FROM rust
COPY --from=builder /usr/src/mano-raje-sh/target/release/backend /usr/local/bin/backend
EXPOSE 8080
CMD ["backend"]
